// data.jsx — fake audit data, shared across views

window.AUDIT_DATA = {
  meta: {
    company: "Northstar Outdoor Co.",
    legal: "Northstar Outdoor Holdings B.V.",
    website: "https://www.northstar-outdoor.com",
    email: "[email protected]",
    phone: "+32 2 555 04 21",
    address: "Rue de la Loi 24, 1040 Brussels, Belgium",
    coordinator: "Eline Janssens",
    lastAudit: "2025-11-04",
    responseTime: "5 business days",
    auditDate: "2026-05-04",
    standard: "WCAG 2.2 AA",
    pagesScanned: 142,
    rulesChecked: 78,
  },

  score: {
    current: 72,
    previous: 58,
    trend: [
      { date: "Jan", score: 41 },
      { date: "Feb", score: 48 },
      { date: "Mar", score: 53 },
      { date: "Apr", score: 58 },
      { date: "May", score: 64 },
      { date: "Jun", score: 72 },
    ],
  },

  severity: {
    errors: 47,
    warnings: 124,
    passed: 1283,
    notice: 36,
  },

  // WCAG POUR principles
  principles: [
    { key: "perceivable",     label: "Perceivable",     errors: 21, warnings: 42, passed: 384, color: "var(--us-lilac)",  textColor: "var(--us-lilac-text)" },
    { key: "operable",        label: "Operable",        errors: 14, warnings: 38, passed: 422, color: "var(--us-mint)",   textColor: "var(--us-mint-text)" },
    { key: "understandable",  label: "Understandable",  errors:  8, warnings: 24, passed: 261, color: "var(--us-sky)",    textColor: "var(--us-sky-text)" },
    { key: "robust",          label: "Robust",          errors:  4, warnings: 20, passed: 216, color: "var(--us-pink)",   textColor: "var(--us-pink-text)" },
  ],

  // Disability impact breakdown
  disabilities: [
    { key: "blind",         label: "Blind / screen reader",     issues: 28, percent: 92, icon: "👁" },
    { key: "lowvision",     label: "Low vision",                issues: 19, percent: 78, icon: "🔍" },
    { key: "deaf",          label: "Deaf / hard of hearing",    issues:  6, percent: 45, icon: "🔊" },
    { key: "motor",         label: "Motor / dexterity",         issues: 14, percent: 64, icon: "🖐" },
    { key: "cognitive",     label: "Cognitive / learning",      issues: 11, percent: 55, icon: "🧠" },
    { key: "seizure",       label: "Seizure / vestibular",      issues:  2, percent: 18, icon: "⚠" },
  ],

  pages: [
    { url: "/",                        title: "Home",                errors: 7, warnings: 14, passed: 89 },
    { url: "/products",                title: "All products",        errors: 9, warnings: 22, passed: 92 },
    { url: "/products/tent-fjord-2p",  title: "Fjord 2P tent",       errors: 6, warnings: 11, passed: 95 },
    { url: "/checkout",                title: "Checkout",            errors: 11, warnings: 18, passed: 82 },
    { url: "/account/orders",          title: "My orders",           errors: 4, warnings: 13, passed: 88 },
    { url: "/blog/winter-base-camp",   title: "Winter base camp",    errors: 3, warnings: 9,  passed: 91 },
    { url: "/about",                   title: "About",               errors: 2, warnings: 7,  passed: 94 },
    { url: "/contact",                 title: "Contact",             errors: 5, warnings: 30, passed: 75 },
  ],

  // Detailed issues (for results dashboard)
  issues: [
    {
      id: "I-001",
      severity: "error",
      principle: "perceivable",
      criterion: "1.1.1",
      title: "Images without alt text",
      rule: "image-alt",
      impact: "blind",
      effort: 4,
      occurrences: 23,
      pages: ["/products", "/products/tent-fjord-2p", "/blog/winter-base-camp"],
      description: "23 product imagery elements are missing meaningful alt text, blocking screen-reader users from understanding the visual content.",
      example: "<img src=\"/img/fjord-tent.jpg\">",
      fix: "<img src=\"/img/fjord-tent.jpg\" alt=\"Orange Fjord 2P tent pitched on a snowy ridge\">",
      wcagLink: "https://www.w3.org/WAI/WCAG22/Understanding/non-text-content",
    },
    {
      id: "I-002",
      severity: "error",
      principle: "perceivable",
      criterion: "1.4.3",
      title: "Insufficient color contrast",
      rule: "color-contrast",
      impact: "lowvision",
      effort: 6,
      occurrences: 14,
      pages: ["/", "/checkout", "/contact"],
      description: "Body copy on cream backgrounds uses #A7A7A7 on #F5F4E5 — a contrast ratio of 2.6:1, well below the 4.5:1 minimum.",
      example: ".muted { color: #A7A7A7; }",
      fix: ".muted { color: #707070; } /* 4.7:1 on cream */",
      wcagLink: "https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum",
    },
    {
      id: "I-003",
      severity: "error",
      principle: "operable",
      criterion: "2.1.1",
      title: "Custom dropdown not keyboard-accessible",
      rule: "keyboard-trap",
      impact: "motor",
      effort: 8,
      occurrences: 6,
      pages: ["/products", "/account/orders"],
      description: "The size-selector dropdown uses div+click handlers; users navigating with Tab cannot focus it, and Enter/Space don't open it.",
      example: "<div class=\"dropdown\" onclick=\"open()\">…</div>",
      fix: "<button type=\"button\" aria-haspopup=\"listbox\" aria-expanded=\"false\">…</button>",
      wcagLink: "https://www.w3.org/WAI/WCAG22/Understanding/keyboard",
    },
    {
      id: "I-004",
      severity: "error",
      principle: "operable",
      criterion: "2.4.7",
      title: "Focus indicator removed",
      rule: "focus-visible",
      impact: "motor",
      effort: 3,
      occurrences: 18,
      pages: ["/", "/products", "/checkout", "/contact"],
      description: "Buttons and links use `outline:none` without replacing the focus ring, leaving keyboard users unable to track their position.",
      example: "button:focus { outline: none; }",
      fix: "button:focus-visible { outline: 2px solid #6257E8; outline-offset: 2px; }",
      wcagLink: "https://www.w3.org/WAI/WCAG22/Understanding/focus-visible",
    },
    {
      id: "I-005",
      severity: "error",
      principle: "understandable",
      criterion: "3.3.2",
      title: "Form inputs missing labels",
      rule: "label",
      impact: "blind",
      effort: 5,
      occurrences: 9,
      pages: ["/checkout", "/contact"],
      description: "Checkout shipping fields rely on placeholders only. Screen readers announce the type but not the field's purpose.",
      example: "<input type=\"text\" placeholder=\"Postal code\">",
      fix: "<label for=\"zip\">Postal code</label>\n<input type=\"text\" id=\"zip\" autocomplete=\"postal-code\">",
      wcagLink: "https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions",
    },
    {
      id: "I-006",
      severity: "error",
      principle: "robust",
      criterion: "4.1.2",
      title: "ARIA roles missing required attributes",
      rule: "aria-required-attr",
      impact: "blind",
      effort: 4,
      occurrences: 4,
      pages: ["/products"],
      description: "Filter sidebar uses role=\"tablist\" but child elements lack role=\"tab\" and aria-controls, breaking the tab semantics for assistive tech.",
      example: "<div role=\"tablist\"><div>Brand</div></div>",
      fix: "<div role=\"tablist\"><button role=\"tab\" aria-controls=\"panel-brand\" aria-selected=\"true\">Brand</button></div>",
      wcagLink: "https://www.w3.org/WAI/WCAG22/Understanding/name-role-value",
    },
    {
      id: "W-001",
      severity: "warning",
      principle: "perceivable",
      criterion: "1.4.10",
      title: "Horizontal scroll at 320px viewport",
      rule: "reflow",
      impact: "lowvision",
      effort: 5,
      occurrences: 11,
      pages: ["/products", "/checkout", "/blog/winter-base-camp"],
      description: "Product grids force horizontal scroll on narrow viewports, breaking reflow for users zoomed in or on small devices.",
      example: ".grid { min-width: 1100px; }",
      fix: ".grid { min-width: 0; } @media (max-width: 700px) { … }",
      wcagLink: "https://www.w3.org/WAI/WCAG22/Understanding/reflow",
    },
    {
      id: "W-002",
      severity: "warning",
      principle: "operable",
      criterion: "2.4.4",
      title: "Link purpose unclear from text alone",
      rule: "link-name",
      impact: "blind",
      effort: 3,
      occurrences: 22,
      pages: ["/", "/blog/winter-base-camp", "/about"],
      description: "Multiple \"Read more\" links don't disambiguate destination when listed by a screen reader.",
      example: "<a href=\"/blog/foo\">Read more</a>",
      fix: "<a href=\"/blog/foo\">Read more <span class=\"sr-only\">about winter base camps</span></a>",
      wcagLink: "https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context",
    },
    {
      id: "W-003",
      severity: "warning",
      principle: "understandable",
      criterion: "3.2.4",
      title: "Inconsistent button labels for same action",
      rule: "consistent-identification",
      impact: "cognitive",
      effort: 2,
      occurrences: 8,
      pages: ["/checkout", "/account/orders"],
      description: "The same checkout action is labelled \"Continue\", \"Next\", and \"Proceed\" across the funnel, increasing cognitive load.",
      example: "<button>Continue</button> … <button>Proceed</button>",
      fix: "Standardize on one verb (\"Continue\") across the funnel.",
      wcagLink: "https://www.w3.org/WAI/WCAG22/Understanding/consistent-identification",
    },
    {
      id: "W-004",
      severity: "warning",
      principle: "robust",
      criterion: "4.1.3",
      title: "Status messages not announced",
      rule: "status-messages",
      impact: "blind",
      effort: 4,
      occurrences: 5,
      pages: ["/checkout", "/contact"],
      description: "The cart-updated toast appears visually but isn't placed in an aria-live region, so screen-reader users miss the confirmation.",
      example: "<div class=\"toast\">Added to cart</div>",
      fix: "<div role=\"status\" aria-live=\"polite\">Added to cart</div>",
      wcagLink: "https://www.w3.org/WAI/WCAG22/Understanding/status-messages",
    },
    {
      id: "P-001",
      severity: "passed",
      principle: "perceivable",
      criterion: "1.3.1",
      title: "Heading structure is logical",
      rule: "heading-order",
      occurrences: 142,
      description: "All scanned pages use a single H1 and a logical heading hierarchy.",
    },
    {
      id: "P-002",
      severity: "passed",
      principle: "robust",
      criterion: "4.1.1",
      title: "Markup parses without errors",
      rule: "valid-html",
      occurrences: 142,
      description: "All pages return valid HTML5 with no duplicate IDs.",
    },
    {
      id: "P-003",
      severity: "passed",
      principle: "operable",
      criterion: "2.4.2",
      title: "Pages have descriptive titles",
      rule: "document-title",
      occurrences: 142,
    },
  ],

  // Sprint suggestion for Jira CTA
  sprint: {
    name: "A11y sprint — May 2026",
    duration: "2 weeks",
    points: 34,
    tickets: [
      { id: "ACC-101", title: "Add alt text to product imagery", points: 5, severity: "error", assignee: "Content team" },
      { id: "ACC-102", title: "Restore visible focus indicators across UI",  points: 3, severity: "error", assignee: "Frontend" },
      { id: "ACC-103", title: "Refactor size-selector to native button + listbox", points: 8, severity: "error", assignee: "Frontend" },
      { id: "ACC-104", title: "Audit + fix color contrast tokens", points: 5, severity: "error", assignee: "Design" },
      { id: "ACC-105", title: "Add labels + autocomplete to checkout fields", points: 5, severity: "error", assignee: "Frontend" },
      { id: "ACC-106", title: "Wrap status toasts in aria-live regions", points: 3, severity: "warning", assignee: "Frontend" },
      { id: "ACC-107", title: "Standardize CTA copy in checkout funnel", points: 2, severity: "warning", assignee: "Content team" },
      { id: "ACC-108", title: "Fix tablist ARIA on /products filter", points: 3, severity: "error", assignee: "Frontend" },
    ],
  },
};
